---
title: "Figure_3_Frechet"
output: html_document
---


```{r}
# import libraries
library(frechet)
library(dplyr)
library(ggplot2)
library(parallel)
library(cowplot)
```

```{r}
### FUNCTION DEFINITIONS
qt2cdf <- function(q_levs, x, y){
  cdf <- approx(x, q_levs, xout = y)
  cdf_vec <- cdf$y
  cdf_vec[y < min(x)] <- 0
  cdf_vec[y > max(x)] <- 1
  return(cdf_vec)
}

qt2pdf <- function(q_levs, x, y){
  n_y <- length(y)
  cdf <- qt2cdf(q_levs, x, y)
  cdf_vec <- c(2*cdf[1] - cdf[2], cdf, 2*cdf[n_y] - cdf[n_y - 1])
  loc_vec <- c(2*y[1] - y[2], y, 2*y[n_y] - y[n_y - 1])
  cdf_c <- c(cdf_vec[3:(n_y + 2)], 0, 0) - cdf_vec
  loc_c <- c(loc_vec[3:(n_y + 2)], 0, 0) - loc_vec
  pdf_vec <- cdf_c / loc_c
  return(pdf_vec[1:n_y])
}

rnormix <- function(n, pi, mu, sigma){
  K <- length(pi)
  res <- rep(0, n)
  for(i in 1:n){
    k <- sample.int(K, 1L, prob=pi)
    res[i] <- rnorm(1, mu[k], sigma[k])
  }
  return(res)
}


```

```{r}
# run the codes
file_list <- list.files('../../Figure_2&3/output/bootstrap_Frechet/')
# parameters
K <- 2
n_dist <- 200
n_sample <- 300
omega <- 0.1
## specify the quantile levels
p_levs <- c(0.1, 0.3, 0.5, 0.7, 0.9)
q_levs <- seq(0, 1, 0.05)
n_levs <- 100
q_sup <- c(0:n_levs) / n_levs
## start training
while (length(file_list) < 500){
  time_start <- Sys.time()
  print(time_start)
  ## simulate the data
  set.seed(length(file_list))
  X <- matrix(runif(n_dist*3, min=-1, max=1), n_dist, 3)
  Y <- matrix(0, n_dist, n_sample)
  for (i in 1:n_dist){
    mu_1 <- X[i, 1]
    mu_2 <- 2 * X[i, 2]^2 + 2
    mu_true <- c(mu_1, mu_2)
    sig_1 <- abs(X[i, 2]) + 0.5
    sig_2 <- abs(X[i, 1]) + 0.5
    sig_true <- c(sig_1, sig_2)
    pi_1 <- 1 / (1 + exp(X[i, 3]))
    pi_true <- c(pi_1, 1-pi_1)
    ## simulate noise
    eps_noise <- rnorm(1, mean = 0, sd = omega)
    ## simulate responses
    var_GMM <- rnormix(n_sample, pi_true, mu_true+eps_noise, sig_true)
    Y[i, ] <- sort(var_GMM)
  }
  
  ## quantiles of the data
  mat_qt_d <- apply(Y, 1, function(x) {quantile(x, p_levs)})
  ## Frechet regression
  mat_qt_X <- apply(X, 2, function(x) {quantile(x, q_levs)})
  ## run regression
  cl <- makeCluster(4, type="SOCK")
  clusterExport(cl, "X")
  clusterExport(cl, "Y")
  clusterExport(cl, "GloDenReg")
  clusterExport(cl, "q_sup")
  res_list <- vector(mode = "list", length = 3)
  for (i in 1:3){
    print(paste('This is variable', i))
    fun_t <- function(x){
      X_c <- X
      X_c[, i] <- x
      res <- GloDenReg(xin=X, yin=Y, xout=X_c, optns = list(qSup = q_sup))
      return(res)
    }
    clusterExport(cl, "i")
    res_list[[i]] <- clusterApply(cl, mat_qt_X[, i], fun_t)
  }
  stopCluster(cl)
  # save the results
  qt_array <- matrix(0, nrow = 3*length(q_levs), ncol = length(p_levs))
  for (i in 1:3){
    for (j in 1:length(q_levs)){
      id_row <- (i - 1) * length(q_levs) + j
      qt_normalize <- apply(res_list[[i]][[j]]$qout, 1, function(x) return(approx(q_sup, x, xout = p_levs)$y))
      qt_array[id_row, ] <- rowMeans(qt_normalize)
    }
  }
  file_list <- list.files('../../Figure_2&3/output/bootstrap_Frechet/')
  file_name <- paste0('../../Figure_2&3/output/bootstrap_Frechet/res_Frechet_qt_', formatC(length(file_list)+1, width=3, flag="0"), '.csv')
  write.csv(qt_array, file = file_name)
  print('Done!')
  print(Sys.time() - time_start)
}
```











