---
title: "Figure3_simulation_CLR"
output: html_document
---

```{r}
# import libraries
library(fda)
library(quadprog)
library(ggplot2)
library(cowplot)
library(gridExtra)
```

```{r}
### FUNCTION DEFINITIONS

# Inverse of CLR transformation 
## Input: z = grid of point defining the abscissa 
##        z_step = step of the grid of the abscissa
##        clr = grid evaluation of the clr transformed density
## Output: grid evaluation of the density
clr2density <- function(z, z_step, clr){
  if (is.fd(clr))
    return(exp(eval.fd(z, clr)) / trapzc(z_step, exp(eval.fd(z, clr))))
  else
    return(exp(clr) / trapzc(z_step, exp(clr)))
}

# Numerical integration via trapezoidal formula
## Input: y = grid evaluation of the function
##        z_step = step of the grid
## Output: numerical integration over the interval
trapzc <- function(step, y){
  n_pts <- length(y)
  res_int <- step * (0.5*y[1] + sum(y[2:(n_pts-1)]) + 0.5*y[n_pts])
  return(res_int)
}

# B-spline fitting of CLR
clr2coef <- function(z, clr, n_knot, y_start, y_end, d = 2){
  norder <- d + 1                 # order of splines (degree + 1)
  nbasis <- n_knot + norder - 2    # g+k+1 (dimension)

  # Create bspline basis
  knots <- seq(y_start, y_end, length=n_knot) # knots
  splajn.basis <- create.bspline.basis(range(knots), nbasis, norder, breaks = knots)

  knot_vec <- c(rep(z[1], d), z, rep(z[n_knot], d))
  knot_diff <- rep(0, nbasis)
  for (i in 1:nbasis){
    knot_diff[i] <- knot_vec[i + norder] - knot_vec[i]
  }

  # Create matrix
  A <- eval.basis(z, splajn.basis)
  b <- clr
  Dmat <- t(A) %*% A
  dvec <- t(b) %*% A
  bvec <- c(0)
  Amat <- matrix(c(knot_diff), nbasis, 1)
  x_sol <- solve.QP(Dmat, dvec, Amat, bvec=bvec, meq = 1)
  return(x_sol$solution)
}

# B-spline coef to density 
coef2density <- function(z, bspline.basis, x){
  beta.fd <- fd(x, bspline.basis)
  beta.l <- eval.fd(z, beta.fd)
  res <- clr2density(z, z[2]-z[1], beta.l)
  return(res)
}

# density to quantile
density2quantile <- function(z, x, q_levs){
  ## Input: z = equally-spaced grid of point defining the abscissa
  z_step <- z[2] - z[1]
  cdf <- cumsum(x) * z_step
  res <- approx(cdf, z, xout = q_levs)
  return(res$y)
}

# density to cdf
density2cdf <- function(z, x, y){
  ## Input: z = equally-spaced grid of point defining the abscissa
  ##        x = density values
  ##        y = grid of output points
  z_step <- z[2] - z[1]
  cdf <- cumsum(x) * z_step
  res <- approx(z, cdf, xout = y)
  return(res$y)
}

rnormix <- function(n, pi, mu, sigma){
  K <- length(pi)
  res <- rep(0, n)
  for(i in 1:n){
    k <- sample.int(K, 1L, prob=pi)
    res[i] <- rnorm(1, mu[k], sigma[k])
  }
  return(res)
}
```

```{r}
# run the codes
file_list <- list.files('../../Figure_2&3/output/bootstrap_CLR/')
# parameters
K <- 2
n_dist <- 200
n_sample <- 300
omega <- 0.1
## specify the quantile levels
p_levs <- c(0.1, 0.3, 0.5, 0.7, 0.9)
q_levs <- seq(0, 1, 0.05)
n_levs <- 100
q_sup <- c(1:(n_levs-1)) / n_levs
## parameter sets
norder_list <- c(2, 3, 4)
nknot_list <- c(5, 8, 10)
## start training
while (length(file_list) < 500){
  time_start <- Sys.time()
  print(time_start)
  ## simulate the data
  set.seed(length(file_list))
  X <- matrix(runif(n_dist*3, min=-1, max=1), n_dist, 3)
  Y <- matrix(0, n_dist, n_sample)
  for (i in 1:n_dist){
    mu_1 <- X[i, 1]
    mu_2 <- 2 * X[i, 2]^2 + 2
    mu_true <- c(mu_1, mu_2)
    sig_1 <- abs(X[i, 2]) + 0.5
    sig_2 <- abs(X[i, 1]) + 0.5
    sig_true <- c(sig_1, sig_2)
    pi_1 <- 1 / (1 + exp(X[i, 3]))
    pi_true <- c(pi_1, 1-pi_1)
    ## simulate noise
    eps_noise <- rnorm(1, mean = 0, sd = omega)
    ## simulate responses
    var_GMM <- rnormix(n_sample, pi_true, mu_true+eps_noise, sig_true)
    Y[i, ] <- sort(var_GMM)
  }
  
  # create count matrix
  ## choose the start points
  eps <- 1e-3
  y_range <- max(Y) - min(Y)
  y_start <- min(Y) - eps
  y_end <- max(Y) + eps
  print(c(y_start, y_end))
  ## choose the number of bins using Sturges rule
  n_bins <- as.integer(1 + log2(dim(Y)[1] * dim(Y)[2]))
  step_size <- (y_end - y_start) / n_bins
  ## calculate the CLR of Y
  loc_breaks <- seq(y_start, y_end, length.out = n_bins + 1)
  Y_count <- apply(Y, 1, function(x) return(hist(x, breaks = loc_breaks, plot = FALSE)$counts))
  
  # apply CLR transformation to count matrix
  ## process the zero counts
  s <- 1 ## Perks prior
  mat_alpha <- rowSums(Y_count) - Y_count
  mat_t <- mat_alpha / colSums(mat_alpha)
  mat_x <- Y_count / colSums(Y_count)
  mat_r <- matrix(0, nrow = nrow(Y_count), ncol = ncol(Y_count))
  Y_comp <- matrix(0, nrow = nrow(Y_count), ncol = ncol(Y_count))
  for (i in 1:ncol(Y_count)){
    for (j in 1:nrow(Y_count)){
      if (mat_x[j, i] == 0){
        mat_r[j, i] <- mat_t[j, i] * s / (s + n_bins)
      }
    }
  }
  for (i in 1:ncol(Y_count)){
    for (j in 1:nrow(Y_count)){
      if (mat_x[j, i] > 0){
        Y_comp[j, i] <- mat_x[j, i] * (1 - sum(mat_r[, i]))
      }
      else{
        Y_comp[j, i] <- mat_r[j, i]
      }
    }
  }
  Y_dens <- Y_comp / step_size
  Y_clr <- apply(Y_dens, 2, function(x) return(log(x) - mean(log(x))))
  
  ## calculate the B-spline coefficient of Y_clr
  y_start <- min(Y) - eps + step_size / 2
  y_end <- max(Y) + eps - step_size / 2
  z <- seq(y_start, y_end, length.out = n_bins)
  loc_fine = seq(y_start, y_end, length.out = 256)
  
  ## train-val split
  loc_CV <- sample(200, replace = FALSE) %% 5
  id_val <- 0
  X_val <- X[loc_CV == id_val, ]
  Y_val <- Y[loc_CV == id_val, ]
  X_train <- X[loc_CV != id_val, ]
  Y_train <- Y[loc_CV != id_val, ]
  
  ## param tuning
  loss_val <- matrix(0, nrow=9, ncol=3)
  for (i in 1:3){
    norder <- norder_list[i]
    for (j in 1:3){
      n_knot <- nknot_list[j]
      nbasis <- n_knot + norder - 2 
      knots <- seq(y_start, y_end, length=n_knot) # knots 
      loss_val[3*i + j - 3, 1] <- norder
      loss_val[3*i + j - 3, 2] <- n_knot
      clr_coef_train <- Y_clr[, loc_CV != id_val]
      Y_coef_train <- apply(clr_coef_train, 2, function(x) return(clr2coef(z, x, n_knot, y_start, y_end, d=norder-1)))
      splajn.basis <- create.bspline.basis(c(y_start, y_end), nbasis, norder, breaks = knots)
      X_train_full <- as.matrix(cbind(rep(1, dim(X_train)[1]), X_train))
      X_val_full <- as.matrix(cbind(rep(1, dim(X_val)[1]), X_val))
      B = solve(t(X_train_full)%*%X_train_full)%*%t(X_train_full)%*%as.matrix(t(Y_coef_train))
      pred_val <- X_val_full %*% B
      dens_val <- t(apply(pred_val, 1, function(x) return(coef2density(loc_fine, splajn.basis, x))))
      quantile_val <- t(apply(dens_val, 1, function(x) return(density2quantile(loc_fine, x, q_levs = q_sup))))
      q_val <-t(apply(Y_val, 1, function(x) {quantile(x, q_sup)}))
      val_loss <- mean((quantile_val - q_val)^2)
      #print(val_loss)
      loss_val[3*i + j - 3, 3] <- loss_val[3*i + j - 3, 3] + val_loss
    }
  }
  
  loc_best <- which.min(loss_val[, 3])
  norder_best <- norder_list[ceiling(loc_best / 3)]
  nknot_best <- nknot_list[(loc_best - 1) %% 3 + 1]
  nbasis_best <- nknot_best + norder_best - 2 
  print(paste('Best par:', c(nknot_best, norder_best)))
  knots_best <- seq(y_start, y_end, length=nknot_best) # knots 
  
  Y_coef <- apply(Y_clr, 2, function(x) return(clr2coef(z, x, nknot_best, y_start, y_end, d=norder_best-1)))
  splajn.basis <- create.bspline.basis(c(y_start, y_end), nbasis_best, norder_best, breaks = knots_best)

  # functional partial dependence plot
  y_levs <- quantile(Y, p_levs)
  mat_qt_X <- apply(X, 2, function(x) {quantile(x, q_levs)})
  qt_array <- matrix(0, nrow = 3*length(q_levs), ncol = length(p_levs))
  ## quantiles of the data
  mat_qt_d <- apply(Y, 1, function(x) {quantile(x, p_levs)})
  for (i in 1:3){
    for (j in 1:length(q_levs)){
      X_c <- X
      X_c[, i] <- mat_qt_X[j, i]
      X_full <- as.matrix(cbind(rep(1, dim(X)[1]), X))
      X_c_full <- as.matrix(cbind(rep(1, dim(X_c)[1]), X_c))
      B = solve(t(X_full)%*%X_full)%*%t(X_full)%*%as.matrix(t(Y_coef))
      pred_mat <- X_c_full %*% B
      ## conditional quantiles
      dens_pred <- t(apply(pred_mat, 1, function(x) return(coef2density(loc_fine, splajn.basis, x))))
      quantile_mat <- t(apply(dens_pred, 1, function(x) return(density2quantile(loc_fine, x, q_levs = p_levs))))
      id_row <- (i - 1) * length(q_levs) + j
      qt_array[id_row, ] <- colMeans(quantile_mat)
    }
  }
  file_list <- list.files('../../Figure_2&3/output/bootstrap_CLR/')
  file_name <- paste0('../../Figure_2&3/output/bootstrap_CLR/res_CLR_qt_', formatC(length(file_list)+1, width=3, flag="0"), '.csv')
  write.csv(qt_array, file = file_name)
  print('Done!')
  print(Sys.time() - time_start)
}
```





